env:
  # Telegram
  TG_CHAT: -1001885973208
  TG_TOKEN: ENCRYPTED[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJwcm90byI6IkNoY0tDbEpsY0c5emFYUnZjbmtRZ0lDdzFMYk9yd29ZQWc9PSIsImlzcyI6ImNpcnJ1cyIsIm93bmVyVWlkIjoiMTM2NjA3OTEyIiwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJwbGF0Zm9ybSI6ImdpdGh1YiJ9.7WTFZGW0d27q5aHPzUyiWbdJo3Ndndu44me9uXlYQi9fOVB-doUmQN8PrtjIWYORFoXVfqG0sPULAvWqRWQkPw]

task:
  name: "KERNEL BUILD CI by TheUnknownName06"
  skip: $CIRRUS_BRANCH == 'master'

  timeout_in: 120m
  container:
      image: ubuntu
      privileged: true
      cpu: 8
      memory: 10G
      
  setup_script:
      - apt update
      - apt upgrade -y
      - apt install wget git -y
      - wget https://raw.githubusercontent.com/TheUnknownName/toolFW/main/setup.sh
      - bash setup.sh

  build_script:
      - wget https://raw.githubusercontent.com/TheUnknownName/Kernel-CI/main/build.sh
      - chmod +x build.sh
      - ./build.sh ${CIRRUS_WORKING_DIR}/name-kernel.txt
